### ISSUE TITLE
Relative protocol in font URL breaks in Chrome extension

### ISSUE THREAD

**Issue by OliverJAsh** [PolymerElements/font-roboto#2]
https://github.com/PolymerElements/paper-styles/blob/d23af125cb74978532c25e5cd152f9b2e6d991c8/typography.html#L11

This will resolve to `chrome://`, which obviously will never work.

Can we be explicit about the protocol?

**Comment by ChrisMcKenzie** [comment]
relative protocol are also now considered an anti-pattern
http://www.paulirish.com/2010/the-protocol-relative-url/

**Comment by jscissr** [comment]
An explicit protocol wouldn't help for Chrome Apps, since external resources are [disallowed](https://developer.chrome.com/apps/contentSecurityPolicy). The only solution is to have a copy of the .css and the font files in this repo. Also +1

**Comment by shycherry** [comment]
same problem when using this with NW.js... +1 !
(will resolve to file:// ...)

**Comment by isaldarriaga** [comment]
same problem for cordova. 
(will resolves to file:// ... )

**Comment by dfreedm** [comment]
Fixed by fcda0585729e698716a89b262c583ed5a24f16ec
