### ISSUE TITLE
Robot Draft vs. Roboto

### ISSUE THREAD

**Issue by OliverJAsh** [PolymerElements/font-roboto#3]
This project seems to use Roboto, but I've seen RobotoDraft used in other projects.

What font should be used?

**Comment by ebidel** [comment]
RobotoDraft was Roboto2, which was finally renamed to Roboto in the Google Fonts API. Anywhere you see RobotoDraft, we should be using "Roboto". Please file bugs wherever you see them!

@notwaldorf @cdata should we tag a release (https://github.com/PolymerElements/font-roboto/issues/1) and start using this import as the canonical in other projects?
